# Generated by Django 4.0.1 on 2022-01-26 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('host', models.GenericIPAddressField()),
                ('port', models.PositiveIntegerField()),
                ('username', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('password', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('to_email', models.EmailField(blank=True, default=None, max_length=254, null=True)),
            ],
        ),
    ]
